version: '2.3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    hostname: cassandra
    volumes:
      - /Users/caitlincjohnson/github/udacity/project_cassandra/cassandra/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
  
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: "zookeeper"
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: "kafka"
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "echo 127.0.0.1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: elasticsearch:7.13.3
    container_name: "elasticsearch"
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      node.store.allow_mmap: "false"

  redis:
    container_name: redis
    image: redis:5.0.4
    ports:
      - "6379:6379"

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      discovery.type: "single-node"


  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:21.7.4.18-alpine
    ports:
      - 8123:8123
      - 9000:9000

     

  superset:
    container_name: superset
    image: superset
    ports:
      - 8080:8088
    



  twitter_fetcher:
    container_name: twitter_fetcher
    build: ./twitter_fetcher

  twitter_preprocess:
    container_name: twitter_preprocess
    build: ./twitter_preprocess
#    command: sh -c "python -u twitter_crowler.py"

  kafka_to_elastic:
    container_name: kafka_to_elastic
    build: ./kafka_to_elastic

  kafka_to_cassandra:
    container_name: kafka_to_cassandra
    build: ./kafka_to_cassandra

  kafka_to_redis:
    container_name: kafka_to_redis
    build: ./kafka_to_redis

  fastapi_to_redis:
    container_name: fastapi_to_redis
    build: ./fastapi_to_redis
    ports:
      - 8086:80



  kafka_to_clickhouse:
    container_name: kafka_to_clickhouse
    build: ./kafka_to_clickhouse
